spring.application.name=api-saude-feminina

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# roda o data.sql depois do Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jackson.time-zone=UTC

app.upload.dir=${UPLOAD_DIR:uploads}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

api.security.token.secret=${JWT_SECRET:3ty7euwtyuighdasbsdhjasv}
api.security.token.expiration=PT24H
