spring.application.name=api-saude-feminina

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jackson.time-zone=UTC

api.security.token.secret=${JWT_SECRET:3ty7euwtyuighdasbsdhjasv}
api.security.token.expiration=PT24H
